rm	load_balancing_bibliography.aux
rm	load_balancing_bibliography.bbl
rm	load_balancing_bibliography.bcf
rm	load_balancing_bibliography.blg
rm	load_balancing_bibliography.log
rm	load_balancing_bibliography.run.xml
